### PR TITLE
For saving time of other developers

### PR DESCRIPTION
**Pull request by buzjuka**

### CODE REVIEW

**Comment by Envek** [comment]
Thank you for contribution!

I guess that you're not using Rails, right? Because for Ruby on Rails we have [railtie that auto-configures Yabeda](https://github.com/yabeda-rb/yabeda/blob/ab2be2235253ed6e0d45a4fa97e4decaa32be480/lib/yabeda/railtie.rb).
What is your stack? Maybe we can add some auto-configuration logic for some other frameworks also.

**Comment by buzjuka** [comment]
Hi. Thanks for response)
No)
I'm using RoR.
Maybe I missed some config lines or something else.
But
This is my environment
```
rails 5.2
puma 4.3.7
yabeda (0.11.0)
```

I have add these lines to my app

```
  # Gemfile.rb
  group :production, :staging do
    gem 'yabeda-puma-plugin'
    gem 'yabeda-prometheus-mmap'
  end
  
```

```
#config/puma.rb

activate_control_app
plugin :yabeda
plugin :yabeda_prometheus
```
And nothing. I have got blank response from `metrics`

After some research. I just add
```
# initializers/yabeda.rb
Yabeda.configure! if Rails.env.production? || Rails.env.staging?
```

Maybe this is bug related to using "single repo" pattern. I don't know.

But I think it could be helpfull for someone else)

**Comment by Envek** [comment]
That's really weird. It should be auto-configured. Thanks for providing details, I will take a look.

**Comment by ollym** [comment]
@Envek just to add, we had exactly the same issue. Rails 6.1 & Ruby 3.0

**Comment by hanyueitaro** [comment]
I had a similar problem.
I created the issue.
https://github.com/yabeda-rb/yabeda-puma-plugin/issues/21

**Pull request merged**
